spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  application:
    name: educationApp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show_sql: 'false'
    hibernate:
      ddl-auto: none
  mail:
    address: example@gmail.com
    host: smtp.gmail.com
    port: 587
    username: mail
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
  t1:
    kafka:
      bootstrap:
        server: localhost:9092
      consumer:
        group-id: t1-demo
        max.poll.records: 10
      producer:
        enable: true
      topic:
        task_status: task_status_topic
      listener:
        poll-timeout: 1000
server:
  port: '8092'

