spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  application:
    name: educationApp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show_sql: 'true'
    hibernate:
      ddl-auto: none
server:
  port: '8092'

