spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  application:
    name: educationApp
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        show_sql: 'false'
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: garnetlicorice
    password: ifwounaqlfgecvxs
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
server:
  port: '8092'

